# This is a generated file. Not intended for manual editing.
version: "3.7"
services:
  api:
    build:
      context: "C:\\Users\\Home\\RiderProjects\\SnapTalk\\src"
      dockerfile: "SnapTalk.WebAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/SnapTalk.WebAPI.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\Home\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\Home\\.nuget\\packages"
    image: "snaptalk.webapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\Home\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\Home\\RiderProjects\\SnapTalk\\src\\SnapTalk.WebAPI:/app:rw"
    - "C:\\Users\\Home\\RiderProjects\\SnapTalk:/src:rw"
    working_dir: "/app"
