version: "3.7"
services:
  api:
    image: vladyslavlintur/converso-api:latest
    ports:
      - "5000:5000"
    restart: on-failure
    container_name: "converso-api"
    depends_on:
      - sql_server
      - azurite
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=sql_server;Database=Converso;User=sa;Password=Password123!;TrustServerCertificate=True"
    env_file:
      - /etc/environment
    networks:
      - back
  
  frontend:
    image: vladyslavlintur/converso-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    depends_on:
      - api
      - sql_server
    networks:
      - back
      - front
  
  sql_server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    networks:
      - back
  
  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"
    container_name: azurite
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"
    restart: on-failure
    networks:
      - back

networks:
  back:
    driver: bridge
  front:
    driver: bridge
  