name: Continuous Delivery

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_api_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push API Service
        uses: docker/build-push-action@v4
        with:
          tags: vladyslavlintur/converso-api:latest
          context: ./src
          file: ./src/Converso.WebAPI/Dockerfile
          push: true
          
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build frontend
        uses: docker/build-push-action@v4
        with:
          tags: vladyslavlintur/converso-frontend:latest
          context: ./src/Converso.Client
          file: ./src/Converso.Client/Dockerfile
          push: true
  deploy_images:
    runs-on: ubuntu-latest
    needs: [ build_frontend, build_api_service ]
    steps:
      - uses: actions/checkout@v3
      - name: Update PROD images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: cd ~/converso && sudo docker-compose -f docker-compose.prod.yml stop && sudo docker-compose -f docker-compose.prod.yml pull && sudo docker system prune -f && sudo docker-compose -f docker-compose.prod.yml up -d